name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  CI:
    runs-on: macos-latest
    env:
      API_LEVEL: 29
      UNIT_TEST_RESUTLS_PATH: $GITHUB_WORKSPACE + "/app/build/test-results/testDebugUnitTest/*.xml"
      CONNECTED_TEST_RESUTLS_PATH: $GITHUB_WORKSPACE + "/app/build/test-results/testDebugUnitTest/*.xml"
    steps:
      - name: Check out Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Set up and Cache Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: Check Kotlin Linting
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintcheck

      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

#            - name: Create AVD and Generate Snapshot for Caching
#              if: steps.avd-cache.outputs.cache-hit != 'true'
#              uses: reactivecircus/android-emulator-runner@v2
#              with:
#                api-level: ${{ env.API_LEVEL }}
#                force-avd-creation: false
#                emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#                disable-animations: false
#                script: echo "generated AVD snapshot for caching"
#
#            - name: Run Connected Android Tests
#              uses: reactivecircus/android-emulator-runner@v2
#              with:
#                api-level: ${{ env.API_LEVEL}}
#                force-avd-creation: false
#                emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#                disable-animations: true
#                script: gradle connectedCheck

      - name: List Path
        if: always()
        run: ls /Users/runner/work/Yatzy/Yatzy/app/build/test-results/testDebugUnitTest/TEST-*.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: |-
            "Unit Tests (w/ absolute Path)"
          report_paths: |-
            "/Users/runner/work/Yatzy/Yatzy/app/build/test-results/testDebugUnitTest/*.xml"
