name: Continuous Integration

on:
  pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Cache Gradle Packages
        if: ${{ github }}
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Lint Kotlin Code
        run: ./gradlew ktlintcheck
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ github }} && always()
        with:
          junit_files: "app/build/test-results/**/*.xml"
